2022-12-15 10:53:25,366 INFO: Microblog startup [in /home/toavina/PycharmProjects/subvers/microblog/app/__init__.py:63]
2022-12-15 10:53:29,134 ERROR: Exception on /edit_profile [POST] [in /home/toavina/PycharmProjects/subvers/microblog/venv/lib/python3.8/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/toavina/PycharmProjects/subvers/microblog/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/home/toavina/PycharmProjects/subvers/microblog/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/toavina/PycharmProjects/subvers/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/toavina/PycharmProjects/subvers/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/toavina/PycharmProjects/subvers/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/toavina/PycharmProjects/subvers/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/toavina/PycharmProjects/subvers/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/toavina/PycharmProjects/subvers/microblog/app/routes.py", line 105, in edit_profile
    db.session.commit()
  File "<string>", line 2, in commit
  File "/home/toavina/PycharmProjects/subvers/microblog/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1451, in commit
    self._transaction.commit(_to_root=self.future)
  File "/home/toavina/PycharmProjects/subvers/microblog/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/home/toavina/PycharmProjects/subvers/microblog/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/home/toavina/PycharmProjects/subvers/microblog/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3444, in flush
    self._flush(objects)
  File "/home/toavina/PycharmProjects/subvers/microblog/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3584, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/toavina/PycharmProjects/subvers/microblog/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/toavina/PycharmProjects/subvers/microblog/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/toavina/PycharmProjects/subvers/microblog/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3544, in _flush
    flush_context.execute()
  File "/home/toavina/PycharmProjects/subvers/microblog/venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/home/toavina/PycharmProjects/subvers/microblog/venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/toavina/PycharmProjects/subvers/microblog/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 237, in save_obj
    _emit_update_statements(
  File "/home/toavina/PycharmProjects/subvers/microblog/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1001, in _emit_update_statements
    c = connection._execute_20(
  File "/home/toavina/PycharmProjects/subvers/microblog/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/toavina/PycharmProjects/subvers/microblog/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/toavina/PycharmProjects/subvers/microblog/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/toavina/PycharmProjects/subvers/microblog/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/home/toavina/PycharmProjects/subvers/microblog/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/home/toavina/PycharmProjects/subvers/microblog/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/toavina/PycharmProjects/subvers/microblog/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/home/toavina/PycharmProjects/subvers/microblog/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: UPDATE user SET username=?, about_me=? WHERE user.id = ?]
[parameters: ('toavina1', 'fjelltopp consultant ??', 2)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
2022-12-15 10:59:08,746 INFO: Microblog startup [in /home/toavina/PycharmProjects/subvers/microblog/app/__init__.py:63]
2022-12-15 11:39:12,948 INFO: Microblog startup [in /home/toavina/PycharmProjects/subvers/microblog/app/__init__.py:63]
2022-12-15 11:39:16,229 INFO: Microblog startup [in /home/toavina/PycharmProjects/subvers/microblog/app/__init__.py:63]
2022-12-15 11:39:30,996 INFO: Microblog startup [in /home/toavina/PycharmProjects/subvers/microblog/app/__init__.py:63]
